// <auto-generated/>
// <Template MiniBrokerClientHandlerFactory.t.t.cs />
// <Version 1.0.0 />
using Microsoft.Extensions.DependencyInjection;
using MiniBroker;
{{Usings}}

namespace {{ClassNamespace}};

public partial class {{ClassName}}: IHandleMessage<{{MessageFullName}}>
{
    async Task IHandleMessage.OnMessage(object message, Context context)
    {
        if (message is {{MessageFullName}} typed)
        {
            await OnMessage(typed, context);
        }
        else
        {
            throw new ArgumentException($"Invalid message type: {message?.GetType().FullName}");
        }
    }
}