// <auto-generated/>
// <Template MiniBrokerClientModule.t.cs />
// <Version 1.0.0 />
using Microsoft.Extensions.DependencyInjection;
using MiniBroker;
{{Usings}}

namespace {{SafeNamespace}};

public static class GeneratedMiniBrokerClientModule
{
    public static void RegisterMiniBrokerSourceHandlers(this IServiceCollection services)
    {
{{HandlerRegistrations}}
    }
    
    private static void AddAsTransient<TService, TImplementation>(this IServiceCollection services, string key)
        where TService : class
        where TImplementation : class, TService, IHandleMessage
    {
        if (!services.Any(s => s.ServiceType == typeof(TImplementation)))
            services.AddTransient<TImplementation>();
        services.AddTransient<TService>(provider => provider.GetRequiredService<TImplementation>());
        services.AddKeyedTransient<IHandleMessage>(key, (provider,_) => provider.GetRequiredService<TImplementation>());
    }

    private static void AddAsScoped<TService, TImplementation>(this IServiceCollection services, string key)
        where TService : class
        where TImplementation : class, TService, IHandleMessage
    {
        if (!services.Any(s => s.ServiceType == typeof(TImplementation)))
            services.AddScoped<TImplementation>();
        services.AddScoped<TService>(provider => provider.GetRequiredService<TImplementation>());
        services.AddKeyedScoped<IHandleMessage>(key, (provider,_) => provider.GetRequiredService<TImplementation>());
    }

    private static void AddAsSingleton<TService, TImplementation>(this IServiceCollection services, string key)
        where TService : class
        where TImplementation : class, TService, IHandleMessage
    {
        if (!services.Any(s => s.ServiceType == typeof(TImplementation)))
            services.AddSingleton<TImplementation>();
        services.AddSingleton<TService>(provider => provider.GetRequiredService<TImplementation>());
        services.AddKeyedSingleton<IHandleMessage>(key, (provider,_) => provider.GetRequiredService<TImplementation>());
    }
}